"""added_player_fields

Revision ID: 047206989442
Revises: ba6d20443266
Create Date: 2022-02-05 20:50:43.672928+02:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '047206989442'
down_revision = 'ba6d20443266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    usertypes = postgresql.ENUM('admin', 'player', name='usertypes')
    usertypes.create(op.get_bind())

    op.add_column('user', sa.Column('instagram', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column(
        'user',
        sa.Column(
            'type', sa.Enum('admin', 'player', name='usertypes'),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    usertypes = postgresql.ENUM('admin', 'player', name='usertypes')
    usertypes.drop(op.get_bind())

    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'instagram')
    # ### end Alembic commands ###
