"""adding_quest_stages

Revision ID: 18c4474458f5
Revises: 863d2de90c3a
Create Date: 2022-01-02 01:41:27.325161+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c4474458f5'
down_revision = '863d2de90c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_stages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_number', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('answer', sa.String(), nullable=False),
        sa.Column('quest_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_quest_stages_id'), 'quest_stages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_stages_id'), table_name='quest_stages')
    op.drop_table('quest_stages')
    # ### end Alembic commands ###
