"""quest_progresses

Revision ID: 354f055b0247
Revises: 63e9099701df
Create Date: 2022-06-12 23:26:17.551054+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354f055b0247'
down_revision = '63e9099701df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('time_to_answer', sa.Interval(), nullable=False),
    sa.Column('current_stage_index', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_progress_id'), 'quests_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quests_progress_id'), table_name='quests_progress')
    op.drop_table('quests_progress')
    # ### end Alembic commands ###
