"""Fri Jun 24 00:15:22 EEST 2022

Revision ID: 84c4623039c2
Revises: 354f055b0247
Create Date: 2022-06-24 00:15:22.915932+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c4623039c2'
down_revision = '354f055b0247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests_progress', sa.Column('answered_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests_progress', 'answered_at')
    # ### end Alembic commands ###
