"""empty message

Revision ID: 863d2de90c3a
Revises: 91979b40eb38
Create Date: 2021-12-26 22:42:46.695069+02:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '863d2de90c3a'
down_revision = '91979b40eb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('start_date', sa.Date(), nullable=True),
                    sa.Column('status', postgresql.ENUM('draft', 'announced',
                                                        'registration',
                                                        'started', 'finished',
                                                        name='queststatuses'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_quest_id'), 'quest', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_id'), table_name='quest')
    op.drop_table('quest')
    # ### end Alembic commands ###
