"""quest registed teams

Revision ID: a31ee84e625f
Revises: ea2c447b9a47
Create Date: 2022-04-24 19:27:58.367664+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31ee84e625f'
down_revision = 'ea2c447b9a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_registered_teams',
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('quest_id', sa.Integer(), nullable=False),
        sa.Column('is_accepted', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
        sa.PrimaryKeyConstraint('team_id', 'quest_id'),
        sa.UniqueConstraint('team_id', 'quest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest_registered_teams')
    # ### end Alembic commands ###
