"""plug_stage_bool

Revision ID: d7f4d49094f5
Revises: 872d6a4fa177
Create Date: 2022-09-18 13:07:04.751810+03:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f4d49094f5'
down_revision = '872d6a4fa177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('has_plug_stage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'has_plug_stage')
    # ### end Alembic commands ###
