"""Sun Jan  2 18:48:56 EET 2022

Revision ID: e995a335ea2f
Revises: 18c4474458f5
Create Date: 2022-01-02 18:48:57.278114+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e995a335ea2f'
down_revision = '18c4474458f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quest_stages', ['order_number', 'quest_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quest_stages', type_='unique')
    # ### end Alembic commands ###
